"""empty message

Revision ID: 1526ba7a56ce
Revises: 
Create Date: 2023-03-09 20:06:30.828776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1526ba7a56ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('anime', sa.String(length=150), nullable=False),
    sa.Column('fav_char', sa.String(length=150), nullable=True),
    sa.Column('ep_watched', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    # ### end Alembic commands ###
